services:
  riemann:
    image: oven/bun:1.2.1-alpine
    container_name: sriemann
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "bun install && bun --hot --watch src/main"
    networks:
      - sriemann
    ports:
      - '${APP_PORT:-3000}:3000'
    environment:
      - NODE_ENV=development
      - APP_PORT=3000

      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

  postgres:
    image: postgres:17
    container_name: sriemann_pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - './docker/data/pgdata:/var/lib/postgresql/data'
    ports:
      - '${FORWARD_POSTGRES_PORT}:5432'
    networks:
      - sriemann

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sriemann

networks:
  sriemann:
    driver: bridge
