services:
  # bun:
  #   image: oven/bun:1.2-alpine
  #   container_name: sriemann_bun
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   command: sh -c "bun install && bun --hot --watch src/main.ts"
  #   networks:
  #     - sriemann
  #   ports:
  #     - "${APP_PORT:-3000}:3000"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "2.0"
  #         memory: 2g

  # bun2:
  #   image: imbios/bun-node:23-alpine
  #   container_name: sriemann_bun
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   command: sh -c "bun install && bun --hot --watch src/main.ts"
  #   networks:
  #     - sriemann
  #   ports:
  #     - "${APP_PORT:-3000}:3000"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "2.0"
  #         memory: 2g

  # node:
  #   image: node:22-alpine
  #   container_name: sriemann
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   command: sh -c "yarn install && yarn run start:dev"
  #   networks:
  #     - sriemann
  #   ports:
  #     - "3000:3000"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "2.0"
  #         memory: 2g

  node:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: sriemann_node
    working_dir: /app
    platform: linux/amd64
    volumes:
      - .:/app
    command: sh -c "yarn install && yarn run start:dev"
    networks:
      - sriemann
    ports:
      - "${APP_PORT:-3000}:3000"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2g

  postgres:
    image: postgres:17
    container_name: sriemann_pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - "./docker/data/pgdata:/var/lib/postgresql/data"
    ports:
      - "${FORWARD_POSTGRES_PORT:-5555}:5432"
    networks:
      - sriemann

  mailpit:
    image: "axllent/mailpit:latest"
    container_name: sriemann_mailpit
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
    networks:
      - sriemann

  # haproxy:
  #   image: haproxy:3.1-alpine
  #   container_name: sriemann_haproxy
  #   ports:
  #     - "${FORWARD_HAPROXY_PORT:-80}:80"
  #     - "${FORWARD_HAPROXY_SSL_PORT:-443}:443"
  #   volumes:
  #     - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  #   networks:
  #     - sriemann
  #   depends_on:
  #     - node
  #     - node1
  #     - postgres
  #     - mailpit

networks:
  sriemann:
    driver: bridge
